### ISSUE TITLE
Mismatched type error

### ISSUE THREAD

**Issue by mehmetcansahin** [Gonzih/crabler#1]
Hi,

When I try to run the sample code, I get the following error. Why do you think it might be?

```
mismatched types

expected enum `std::result::Result`, found enum `std::option::Option`

note: expected enum `std::result::Result<WorkOutput, async_std::sync::channel::RecvError>`
         found enum `std::option::Option<_>`rustc(E0308)
lib.rs(175, 20): expected enum `std::result::Result`, found enum `std::option::Option`
lib.rs(175, 35): this expression has type `std::result::Result<WorkOutput, async_std::sync::channel::RecvError>
```

**Comment by Gonzih** [comment]
Hey, could you paste example code you are running?

**Comment by mehmetcansahin** [comment]
rust 1.44.0
rustup 1.21.1 (7832b2ebe 2019-12-20)
cargo 1.44.0 (05d080faa 2020-05-06)

Example code:
```
extern crate crabler;

use crabler::*;

#[derive(WebScraper)]
#[on_response(response_handler)]
#[on_html("a[href]", print_handler)]
struct Scraper {}

impl Scraper {
    async fn response_handler(&self, response: Response) -> Result<()> {
        println!("Status {}", response.status);
        Ok(())
    }

    async fn print_handler(&self, response: Response, a: Element) -> Result<()> {
        if let Some(href) = a.attr("href") {
            println!("Found link {} on {}", href, response.url);
        }

        Ok(())
    }
}

#[tokio::main]
async fn main() -> Result<()> {
    let scraper = Scraper {};

    // Run scraper starting from given url and using 20 worker threads
    scraper.run(Opts::new().with_urls(vec!["https://news.ycombinator.com/"]).with_threads(20)).await
}
```

**Comment by Gonzih** [comment]
This is weird, cant figure out what the problem is and where this error is coming from based on your trace.

Here is a working project of mine that uses this library, can you maybe take a look and compare to your setup? Maybe that will point to the issue.

https://github.com/Gonzih/apod-nasa-scraper-rs

**Comment by mehmetcansahin** [comment]
https://github.com/Gonzih/apod-nasa-scraper-rs => I had no problems in this project.

https://github.com/mehmetcansahin/crabler_test_project => Example project. Can you test this project?

**Comment by Gonzih** [comment]
Tested your project, looks like api in async std has changes and your library pulled the latest version. I will fix this and release new version soon. Thanks for reporting this, great catch!

**Comment by mehmetcansahin** [comment]
Thank you.

**Comment by Gonzih** [comment]
New resion is out, please give it a try.
`crabler = "0.1.12"`
