### ISSUE TITLE
HTTP 301 redirects can't be followed

### ISSUE THREAD

**Issue by Susurrus** [Gonzih/crabler#6]
I'm trying to use Crabler to do some basic web scraping and I've run into an issue where 301 redirects aren't followed. I can't implement a way to handle this in my own code, because the redirect URL from the response isn't exposed to the `on_response` callback. An alternative implementation would be to change this in the `Crabler::event_loop` when other HTTP status codes are checked and to handle the redirect transparently. For my application, I think either approach would work, but given that Download implements similar functionality, I think implementing a similar approach for 301 redirects would make sense.

**Comment by Gonzih** [comment]
Im fine with having follow_redirect as an option in crabler somewhere. Crabler uses surf underneath (https://docs.rs/surf/2.3.2/surf/), but i havent looked into how surf client can be forced to do redirects. PRs are welcome :P

**Comment by Susurrus** [comment]
I will definitely need this functionality, so I'll try to take a stab at it. I expect I should add this as an additional field to `crabler::Opt`, I'm thinking of a default value of `true` would make sense. I would expect a webcrawler that has this level of indirection would automatically follow redirects. Do you think that's the right default?

**Comment by Susurrus** [comment]
An alternative implementation would be to expose the redirection URL and leave it up to someone's custom implementation of `on_response` to deal with following any redirections, since it's possible to add pages to be queried through the `navigate` method. That's more boilerplate for a user that "just wants to scrape all pages", but a bunch more flexibility.

If I implement it with automatically following 3xx redirects, should I hide those responses from the `on_response` handler if one exists? Or still expose them there? Exposing them there gets into an ordering issue, so I guess it'd make sense to run the user's callback then follow the redirect.

**Comment by Gonzih** [comment]
Yes, default value in Opts is how I would approach this! Crawler should follow redirects, unless specified otherwise for the sake of convenience i think.
