### ISSUE TITLE
No way to get text of the entire page

### ISSUE THREAD

**Issue by Susurrus** [Gonzih/crabler#8]
I'm trying to get the page title and body text to cache for local searching. However, using `html`, `body`, etc. don't allow me to get the text of the entire page. I can use `title` as a selector to get the page title, but if I can't get the body text at the same time, I can't easily save those together into my local cache (I'd like to use a `(title, body)` tuple for saving them). Is there something I'm missing here? Would resolving this be in-scope for crabler?

If I'm thinking about implementing it, I was thinking of a new `on_page` handler that would provide the entire page in one request that would compliment the existing `on_html` handler. Would that be in scope for this library?

**Comment by Gonzih** [comment]
Gathering body text wouild involve walking over entire tree of elements under body in search of text nodes and concatenating them. Most of libraries do this under the hood when you invoke .text() method or something similar. Im not oposing to have a method like that in crabler, but i dont have any plans atm to add it myself. PRs are always welcome. Hope that clarifies things.

**Comment by Susurrus** [comment]
I need this functionality, so was considering adding it, though I'm liking your comment about the body, maybe call it `on_body`. I don't see a reason to include the `<head>` in this part, as the use case is to get all the text of the actual page, which shouldn't come from anything in `<head>`.

Would it make sense to call `.text()` on everything or instead pull all the raw text and strip out any and all tags afterwards? I would think the latter approach would be faster, though probably benchmarking is in order...

**Comment by Susurrus** [comment]
So I'm thinking that the issue is really that there's no way to get the "raw" source of an element from `crabquery::Element` from what I can tell. I could `on_html(body, ...)` and then call `html()` (which is what jQuery uses I think) to get the interior HTML. Then I could extract everything I need from there. But it looks like `crabquery` is a separate lib, would it be reasonable to add such a method there? I think that's the most versatile approach.

**Comment by Gonzih** [comment]
you can add `full_text` method to `crabquery::Element` that would simply first call `text()` method and then get `children()` of a node and append all the `full_text()` calls from those to a string.

**Comment by Gonzih** [comment]
you can probably also extend crabquery::Element if you implement your own trait in your code and then implement it on `Element` type (you can implement your own traits on 3rd party types).

**Comment by Gonzih** [comment]
and yeah, you can send PR to crabquery library, its fine. I would publish it then and update dependencies in crabler.
